### ISSUE TITLE
JavaScript group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by StevenWafeek** [StevenWafeek/Javascript-Capstone#21]
**This is the link to our project** [git-hub project link](https://github.com/StevenWafeek/Javascript-Capstone/projects/1)
We are two coding partners working on this kanban_board project:
- Matembe Benjamin
- Steven Wafeek

We have created this following the guidelines in the Microverse module 2 capstone project requirements

**Comment by GzimAsani** [comment]
### Hello, @AyomipoMajek                 :wave:   
 Good job so far,  done There are some issues that you still need to work on to go to the next project but you are almost there!
 
 ## Highlights
 * Good job with your files, everything looks great you just have to update 2 details :+1: 

 ## Required Changes 

- [ ] All the task should be assigned to their respective person
- [ ] Divide tasks in a fair way 

![image](https://github.com/StevenWafeek/Javascript-Capstone/assets/62705947/66f9deca-cd7e-4c33-a438-f685300ba95f)

 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding! clapclapclap
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by BenjaminMatembe** [comment]
Thank you @Zuhaib042 for the approval,  @GzimAsani for the highlights ,@addod19 for the highlights.
This keeps us going 👍
